name: Changed files DEV

# This will act on changed files in any push (except to master) and on
# pull request tests.
on:
  push:
    branches-ignore:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-changed-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for 'on: push'
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45  # use full hash
        with:
          files: |
            dir/*.yml
            dir/*.yaml
      - name: List detected changed files
        env:
          CHANGED: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for filename in ${CHANGED}  ; do
            echo "$filename was changed"
            echo "::notice title=Updated::${filename}"
          done
