name: Changed files test

on:
  push:
    branches:
      - master

jobs:
  test-changed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # needed for 'on: push'
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            dir/*.yml
            dir/*.yaml
      - name: List detected changed files
        env:
          CHANGED: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          for filename in ${CHANGED}  ; do
            echo "$filename was changed"
            echo "::notice title=Updated::${filename}"
          done
